{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "7980\n",
      "Fitbit Plus\n",
      "22349\n",
      "IPods\n",
      "999\n",
      "MI Band\n",
      "2799\n",
      "Cult Pass\n",
      "229900\n",
      "Macbook Pro\n",
      "11101\n",
      "Digital Camera\n",
      "9999\n",
      "Alexa\n",
      "2195\n",
      "Sandwich Toaster\n",
      "9800\n",
      "Microwave Oven\n",
      "4999\n",
      "Scale\n",
      "{'Fitbit Plus': '7980', 'IPods': '22349', 'MI Band': '999', 'Cult Pass': '2799', 'Macbook Pro': '229900', 'Digital Camera': '11101', 'Alexa': '9999', 'Sandwich Toaster': '2195', 'Microwave Oven': '9800', 'Scale': '4999'}\n",
      "[229900, 22349, 11101, 9999, 9800, 7980, 4999, 2799, 2195, 999]\n",
      "Number of the employees: 5\n",
      "employees 5\n",
      "5\n",
      "difference 7200\n",
      "7980\n",
      "Fitbit Plus: 7980\n",
      "22349\n",
      "999\n",
      "2799\n",
      "Cult Pass: 2799\n",
      "229900\n",
      "11101\n",
      "9999\n",
      "Alexa: 9999\n",
      "2195\n",
      "9800\n",
      "Microwave Oven: 9800\n",
      "4999\n",
      "Scale: 4999\n"
     ]
    }
   ],
   "source": [
    "# open file to read input\n",
    "sample_input = open('C:/Users/sindhu s/Desktop/High peak coding test/sample_input.txt','r')\n",
    "\n",
    "\n",
    "# open output file to write and append in old file\n",
    "\n",
    "\n",
    "# To append some text to a file in the end, we first need to open the file with access mode ‘a’,\n",
    "sample_output = open('C:/Users/sindhu s/Desktop/High peak coding test/sample_output.txt','a')\n",
    "\n",
    "goodies={}\n",
    "output_list=[]\n",
    "\n",
    "\n",
    "# read the input file and strip goodies and values\n",
    "for f in sample_input:\n",
    "    index_toRead_price=f.index(\":\")\n",
    "    print(f[index_toRead_price+1:].strip())\n",
    "    print(f[:index_toRead_price])\n",
    "    goodies[f[:index_toRead_price]]=f[index_toRead_price+1:].strip()\n",
    "print(goodies)\n",
    "\n",
    "\n",
    "# prices=list(goodies.values())\n",
    "\n",
    "prices=[int(i) for i in list(goodies.values())]\n",
    "# prices_v=list(goodies.values())\n",
    "\n",
    "\n",
    "# sort the price in descending order it will be easy to distribute the order\n",
    "prices.sort(reverse=True)\n",
    "print(prices)\n",
    "\n",
    "\n",
    "# get the employees\n",
    "employees=int(input(\"Number of the employees: \"))\n",
    "print(\"employees\",employees)\n",
    "\n",
    "length_considered=(len(prices)- employees)\n",
    "\n",
    "print(length_considered)\n",
    "\n",
    "for i in range(length_considered):\n",
    "    maxprice=prices[i]\n",
    "    minprice=prices[employees+i]\n",
    "    if i == 0:\n",
    "        difference=maxprice-minprice\n",
    "        choosen_index=i\n",
    "    elif (maxprice-minprice)<difference:\n",
    "        difference=maxprice-minprice\n",
    "        choosen_index=i\n",
    "# find the difference between max and min price\n",
    "\n",
    "c_price=prices[choosen_index:employees+choosen_index]\n",
    "\n",
    "difference=max(c_price)-min(c_price)\n",
    "print(\"difference\",difference)\n",
    "\n",
    "\n",
    "\n",
    "count=0\n",
    "\n",
    "for key,value in goodies.items():\n",
    "    prices[count]\n",
    "    print(value)\n",
    "    if int(value) in c_price and count < employees:\n",
    "        str1=key+\": \"+value\n",
    "\n",
    "# append the data in list of order and employees\n",
    "        output_list.append(str1)\n",
    "        count+=1\n",
    "        print(str1)\n",
    "\n",
    "sample_output.write(\"Number of employees: \"+str(employees))\n",
    "sample_output.write(\"\\n\\n\")\n",
    "\n",
    "# selected goodies\n",
    "sample_output.write(\"Here the goodies that are selected for distribution are: \")\n",
    "\n",
    "sample_output.write(\"\\n\")\n",
    "\n",
    "for i in output_list:\n",
    "    sample_output.write(i)\n",
    "    sample_output.write(\"\\n\")\n",
    "sample_output.write(\"And the difference between the chosen goodie with highest price and the lowest price is \"+str(difference))\n",
    "sample_output.write(\"\\n\\n\\n\")\n",
    "\n",
    "\n",
    "sample_input.close()\n",
    "sample_output.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
